import type { InterfaceLanguage } from "@/context/interface-language";

type LocalizedCopy = { en: string; pt: string };

const COPY: Record<string, LocalizedCopy> = {
  "Traducción y verificación médica": { en: "Medical translation and verification", pt: "Tradução e verificação médica" },
  "Abrir el traductor": { en: "Open translator", pt: "Abrir tradutor" },
  "Medicina humana y veterinaria · One Health": { en: "Human and veterinary medicine · One Health", pt: "Medicina humana e veterinária · One Health" },
  "Del lenguaje del paciente": { en: "From the patient's language", pt: "Da linguagem do paciente" },
  "al artículo indexado.": { en: "to the indexed article.", pt: "ao artigo indexado." },
  "Traducir un texto": { en: "Translate text", pt: "Traduzir texto" },
  "Subir un documento": { en: "Upload a document", pt: "Enviar um documento" },
  "Trazabilidad científica": { en: "Scientific traceability", pt: "Rastreabilidade científica" },
  "Abrir": { en: "Open", pt: "Abrir" },
  "Tus proyectos médicos, siempre disponibles": { en: "Your medical projects, always available", pt: "Seus projetos médicos, sempre disponíveis" },
  "Acceso privado por invitación": { en: "Private access by invitation", pt: "Acesso privado por convite" },
  "Ingresa con el correo autorizado por el administrador.": { en: "Sign in with the email authorized by the administrator.", pt: "Entre com o e-mail autorizado pelo administrador." },
  "Correo electrónico": { en: "Email", pt: "E-mail" },
  "Contraseña": { en: "Password", pt: "Senha" },
  "Procesando…": { en: "Processing…", pt: "Processando…" },
  "Entrar": { en: "Sign in", pt: "Entrar" },
  "Tus proyectos y documentos se guardan de forma privada y solo estarán disponibles dentro de tu cuenta.": { en: "Your projects and documents are stored privately and are only available in your account.", pt: "Seus projetos e documentos são armazenados de forma privada e ficam disponíveis somente em sua conta." },
  "Detectar idioma": { en: "Detect language", pt: "Detectar idioma" },
  "automático": { en: "automatic", pt: "automático" },
  "neutro": { en: "neutral", pt: "neutro" },
  "Detectar automáticamente": { en: "Detect automatically", pt: "Detectar automaticamente" },
  "Nivel de complejidad": { en: "Complexity level", pt: "Nível de complexidade" },
  "Ámbito": { en: "Scope", pt: "Área" },
  "Paciente": { en: "Patient", pt: "Paciente" },
  "Divulgación": { en: "General audience", pt: "Divulgação" },
  "Clínico": { en: "Clinical", pt: "Clínico" },
  "Científico": { en: "Scientific", pt: "Científico" },
  "humana": { en: "human", pt: "humana" },
  "Veterinaria": { en: "Veterinary", pt: "Veterinária" },
  "Copiar": { en: "Copy", pt: "Copiar" },
  "Copiado": { en: "Copied", pt: "Copiado" },
  "Traducir": { en: "Translate", pt: "Traduzir" },
  "Traduciendo…": { en: "Translating…", pt: "Traduzindo…" },
  "Cotejar": { en: "Verify", pt: "Verificar" },
  "Cotejando…": { en: "Verifying…", pt: "Verificando…" },
  "Cotejar en fuentes": { en: "Verify in sources", pt: "Verificar nas fontes" },
  "Texto original": { en: "Original text", pt: "Texto original" },
  "Traducción": { en: "Translation", pt: "Tradução" },
  "Resultado": { en: "Result", pt: "Resultado" },
  "Descargar": { en: "Download", pt: "Baixar" },
  "Descargar Word": { en: "Download Word", pt: "Baixar Word" },
  "Descargar PDF": { en: "Download PDF", pt: "Baixar PDF" },
  "Descargar TXT": { en: "Download TXT", pt: "Baixar TXT" },
  "Suelta el archivo .txt aquí": { en: "Drop the .txt file here", pt: "Solte o arquivo .txt aqui" },
  "Suelta el archivo aquí": { en: "Drop the file here", pt: "Solte o arquivo aqui" },
  "Suelta el artículo aquí": { en: "Drop the article here", pt: "Solte o artigo aqui" },
  "Seleccionar archivo": { en: "Choose file", pt: "Selecionar arquivo" },
  "Arrastra o selecciona un archivo": { en: "Drag or choose a file", pt: "Arraste ou selecione um arquivo" },
  "Revisar": { en: "Proofread", pt: "Revisar" },
  "Revisando…": { en: "Proofreading…", pt: "Revisando…" },
  "Puntuación global": { en: "Overall score", pt: "Pontuação geral" },
  "En texto:": { en: "In text:", pt: "No texto:" },
  "Correcto:": { en: "Correct:", pt: "Correto:" },
  "Otras lecturas:": { en: "Other meanings:", pt: "Outras interpretações:" },
  "correcto": { en: "correct", pt: "correto" },
  "revisar": { en: "review", pt: "revisar" },
  "Sin incidencias": { en: "No issues", pt: "Sem ocorrências" },
  "Informe": { en: "Report", pt: "Relatório" },
  "Descargar informe": { en: "Download report", pt: "Baixar relatório" },
  "Descargar informe Word": { en: "Download Word report", pt: "Baixar relatório Word" },
  "Sigla / abreviatura / término": { en: "Acronym / abbreviation / term", pt: "Sigla / abreviação / termo" },
  "Idioma de la abreviatura": { en: "Abbreviation language", pt: "Idioma da abreviação" },
  "Explicar en": { en: "Explain in", pt: "Explicar em" },
  "Contexto donde aparece (opcional, mejora mucho la precisión)": { en: "Context where it appears (optional, greatly improves accuracy)", pt: "Contexto em que aparece (opcional, melhora muito a precisão)" },
  "País de uso (opcional)": { en: "Country of use (optional)", pt: "País de uso (opcional)" },
  "Descifrar": { en: "Decode", pt: "Decifrar" },
  "Analizando…": { en: "Analyzing…", pt: "Analisando…" },
  "¿Qué significa esta sigla?": { en: "What does this acronym mean?", pt: "O que significa esta sigla?" },
  "Añadir al glosario": { en: "Add to glossary", pt: "Adicionar ao glossário" },
  "Documentos recientes": { en: "Recent documents", pt: "Documentos recentes" },
  "Historial de proyectos": { en: "Project history", pt: "Histórico de projetos" },
  "Traducir documento": { en: "Translate document", pt: "Traduzir documento" },
  "Buscar…": { en: "Search…", pt: "Buscar…" },
  "Sin traducir": { en: "Not translated", pt: "Não traduzido" },
  "Retomar": { en: "Resume", pt: "Retomar" },
  "Borrar": { en: "Delete", pt: "Excluir" },
  "Los documentos que abras aparecerán aquí automáticamente.": { en: "Documents you open will appear here automatically.", pt: "Os documentos que você abrir aparecerão aqui automaticamente." },
  "Traducir subtítulos": { en: "Translate subtitles", pt: "Traduzir legendas" },
  "Traducción terminada": { en: "Translation complete", pt: "Tradução concluída" },
  "Extrayendo pista de audio del vídeo…": { en: "Extracting audio track from video…", pt: "Extraindo faixa de áudio do vídeo…" },
  "Preparando el archivo…": { en: "Preparing file…", pt: "Preparando arquivo…" },
  "Mantén esta pestaña abierta durante el procesamiento.": { en: "Keep this tab open during processing.", pt: "Mantenha esta aba aberta durante o processamento." },
  "Transcripción automática": { en: "Automatic transcription", pt: "Transcrição automática" },
  "Traducción médica": { en: "Medical translation", pt: "Tradução médica" },
  "Subtítulos": { en: "Subtitles", pt: "Legendas" },
  "Original": { en: "Original", pt: "Original" },
  "Generar y validar": { en: "Generate and validate", pt: "Gerar e validar" },
  "Extrayendo metadatos del artículo…": { en: "Extracting article metadata…", pt: "Extraindo metadados do artigo…" },
  "Coincidencias en portales científicos": { en: "Matches in scientific databases", pt: "Correspondências em portais científicos" },
  "estilo activo": { en: "active style", pt: "estilo ativo" },
  "Guardar en bibliografía": { en: "Save to bibliography", pt: "Salvar na bibliografia" },
  "Bibliografía guardada": { en: "Saved bibliography", pt: "Bibliografia salva" },
  "Eliminar": { en: "Delete", pt: "Excluir" },
  "Sube el artículo o tesis en PDF": { en: "Upload the article or thesis as a PDF", pt: "Envie o artigo ou a tese em PDF" },
  "Auditar bibliografía": { en: "Audit bibliography", pt: "Auditar bibliografia" },
  "Auditando…": { en: "Auditing…", pt: "Auditando…" },
  "retractada": { en: "retracted", pt: "retratada" },
  "Idiomas habilitados": { en: "Enabled languages", pt: "Idiomas habilitados" },
  "Glosario personal": { en: "Personal glossary", pt: "Glossário pessoal" },
  "Término o sigla de origen": { en: "Source term or acronym", pt: "Termo ou sigla de origem" },
  "Equivalente obligatorio": { en: "Required equivalent", pt: "Equivalente obrigatório" },
  "Añadir término": { en: "Add term", pt: "Adicionar termo" },
  "Eliminar término": { en: "Delete term", pt: "Excluir termo" },
  "base": { en: "core", pt: "base" },
  "Idioma de la interfaz": { en: "Interface language", pt: "Idioma da interface" },
  "Traducción clínica": { en: "Clinical translation", pt: "Tradução clínica" },
  "Glosario automático": { en: "Automatic glossary", pt: "Glossário automático" },
  "Bidireccional entre español, inglés, portugués y francés, con variante por país y cuatro niveles: de lenguaje de paciente a artículo indexado.": { en: "Bidirectional translation between Spanish, English, Portuguese and French, with country variants and four levels—from patient language to indexed articles.", pt: "Tradução bidirecional entre espanhol, inglês, português e francês, com variantes por país e quatro níveis — da linguagem do paciente ao artigo indexado." },
  "Doble corrección": { en: "Dual proofreading", pt: "Dupla revisão" },
  "Doble check": { en: "Dual check", pt: "Dupla verificação" },
  "Revisa ortografía, tipografía médica y verifica cada abreviatura, sigla y acrónimo contra su uso correcto en contexto — con alerta ISMP de siglas peligrosas.": { en: "Checks spelling and medical typography and verifies every abbreviation and acronym in context—with ISMP alerts for dangerous abbreviations.", pt: "Revisa ortografia e tipografia médica e verifica cada abreviação e sigla no contexto — com alertas ISMP para siglas perigosas." },
  "Siglas y abreviaturas": { en: "Acronyms and abbreviations", pt: "Siglas e abreviações" },
  "Cotejo científico": { en: "Scientific verification", pt: "Verificação científica" },
  "Todas las lecturas posibles ordenadas por probabilidad, uso por país, códigos normalizados y alerta de abreviaturas peligrosas.": { en: "All possible meanings ranked by probability, country usage and standardized codes, with dangerous-abbreviation alerts.", pt: "Todas as interpretações possíveis ordenadas por probabilidade, uso por país e códigos padronizados, com alertas de abreviações perigosas." },
  "Documentos": { en: "Documents", pt: "Documentos" },
  "Formato intacto": { en: "Formatting preserved", pt: "Formatação preservada" },
  "PDF, Word y PowerPoint traducidos sobre el propio archivo: se conserva el diseño, se editan segmento a segmento y se descargan.": { en: "Translate PDF, Word and PowerPoint files in place while preserving layout, with segment-by-segment editing and download.", pt: "Traduza arquivos PDF, Word e PowerPoint preservando o layout, com edição segmento a segmento e download." },
  "Vídeo y subtítulos": { en: "Video and subtitles", pt: "Vídeo e legendas" },
  "Sube un vídeo o audio médico: se transcribe el audio, se generan subtítulos con timestamps y se traducen al idioma que elijas.": { en: "Upload a medical video or audio file to transcribe it, create timestamped subtitles and translate them into your chosen language.", pt: "Envie um vídeo ou áudio médico para transcrever, gerar legendas com timestamps e traduzi-las para o idioma escolhido." },
  "Citas bibliográficas": { en: "Bibliographic citations", pt: "Citações bibliográficas" },
  "Validez comprobada": { en: "Verified validity", pt: "Validade verificada" },
  "APA 7.ª, AMA 11.ª y Vancouver generadas desde un DOI, un PMID o texto libre, con validación en Crossref y PubMed.": { en: "Generate APA 7th, AMA 11th and Vancouver citations from a DOI, PMID or free text, validated against Crossref and PubMed.", pt: "Gere citações APA 7ª, AMA 11ª e Vancouver a partir de DOI, PMID ou texto livre, validadas no Crossref e PubMed." },
  "Auditoría de bibliografía": { en: "Bibliography audit", pt: "Auditoria bibliográfica" },
  "Detecta retractaciones": { en: "Detects retractions", pt: "Detecta retratações" },
  "Cruza las citas del PDF con su bibliografía, verifica que los estudios existan aunque estén en otro idioma y propone correcciones.": { en: "Cross-checks PDF citations against the bibliography, verifies that studies exist even in other languages and suggests corrections.", pt: "Cruza as citações do PDF com a bibliografia, verifica se os estudos existem mesmo em outros idiomas e sugere correções." },
  "Bidireccional, por país y por nivel de complejidad — de lenguaje de paciente a artículo indexado.": { en: "Bidirectional, by country and complexity level—from patient language to indexed articles.", pt: "Bidirecional, por país e nível de complexidade — da linguagem do paciente ao artigo indexado." },
  "Ortografía, tipografía médica y verificación de cada abreviatura, sigla y acrónimo con cotejo en fuentes.": { en: "Spelling, medical typography and source verification for every abbreviation and acronym.", pt: "Ortografia, tipografia médica e verificação em fontes de cada abreviação e sigla." },
  "Descifra siglas, abreviaturas, contracciones y símbolos médicos, con su uso por país y su cotejo científico.": { en: "Decodes medical acronyms, abbreviations, contractions and symbols, including country usage and scientific verification.", pt: "Decifra siglas, abreviações, contrações e símbolos médicos, incluindo uso por país e verificação científica." },
  "Traduce PDF, Word y PowerPoint sobre el propio documento, edítalos y descárgalos con el formato original.": { en: "Translate PDF, Word and PowerPoint files in place, edit them and download them in their original format.", pt: "Traduza PDF, Word e PowerPoint no próprio documento, edite-os e baixe-os no formato original." },
  "Sube un vídeo o audio médico: MedLingua transcribe el audio, genera subtítulos y los traduce al idioma que elijas.": { en: "Upload medical video or audio: MedLingua transcribes it, creates subtitles and translates them into your chosen language.", pt: "Envie vídeo ou áudio médico: o MedLingua transcreve, cria legendas e traduz para o idioma escolhido." },
  "Sube el artículo en PDF, Word o PowerPoint — o pega un DOI/PMID — y genera la cita en APA, AMA o Vancouver con validación en Crossref y PubMed.": { en: "Upload a PDF, Word or PowerPoint article—or paste a DOI/PMID—to generate an APA, AMA or Vancouver citation validated against Crossref and PubMed.", pt: "Envie o artigo em PDF, Word ou PowerPoint — ou cole um DOI/PMID — para gerar a citação em APA, AMA ou Vancouver validada no Crossref e PubMed." },
  "Comprueba que las citas del PDF coincidan con la bibliografía y que los estudios citados existan, aunque estén en otro idioma.": { en: "Checks that PDF citations match the bibliography and that cited studies exist, even in another language.", pt: "Verifica se as citações do PDF correspondem à bibliografia e se os estudos citados existem, mesmo em outro idioma." },
  "Pega aquí un informe clínico, un consentimiento informado, un abstract o una ficha técnica… También puedes arrastrar un .txt": { en: "Paste a clinical report, informed consent, abstract or technical sheet here… You can also drag in a .txt file", pt: "Cole aqui um relatório clínico, consentimento informado, resumo ou ficha técnica… Você também pode arrastar um arquivo .txt" },
  "Pega aquí un informe, historia clínica, abstract o ficha técnica para revisar ortografía, abreviaturas y siglas…": { en: "Paste a report, medical record, abstract or technical sheet to check spelling, abbreviations and acronyms…", pt: "Cole um relatório, prontuário, resumo ou ficha técnica para revisar ortografia, abreviações e siglas…" },
  "Pega la frase completa: «…se activa código IAM y se traslada a UCIC…»": { en: "Paste the full sentence: “…STEMI protocol is activated and the patient is transferred to the CCU…”", pt: "Cole a frase completa: “...o protocolo IAM é ativado e o paciente é transferido para a UCO...”" },
  "México, Brasil, Francia…": { en: "Mexico, Brazil, France…", pt: "México, Brasil, França…" },
  "Arrastra tu documento o haz clic": { en: "Drag your document or click", pt: "Arraste seu documento ou clique" },
  "Arrastra tu vídeo o audio, o haz clic": { en: "Drag your video or audio, or click", pt: "Arraste seu vídeo ou áudio, ou clique" },
  "Ajustes": { en: "Settings", pt: "Configurações" },
  "Idiomas disponibles": { en: "Available languages", pt: "Idiomas disponíveis" },
  "Activa idiomas adicionales, elige la variante de cada país y fija tu glosario institucional.": { en: "Enable additional languages, choose country variants and define your institutional glossary.", pt: "Ative idiomas adicionais, escolha variantes por país e defina seu glossário institucional." },
  "Estilo de cita preferido": { en: "Preferred citation style", pt: "Estilo de citação preferido" },
  "Se usa en el módulo de citas y en la auditoría": { en: "Used in the citations and audit modules", pt: "Usado nos módulos de citações e auditoria" },
  "Se aplica de forma obligatoria en cada traducción": { en: "Applied to every translation", pt: "Aplicado obrigatoriamente em cada tradução" },
  "Se guarda en este navegador": { en: "Saved in this browser", pt: "Salvo neste navegador" },
  "Traducción médica bidireccional especializada en siglas, abreviaturas, contracciones y epónimos — incluyendo su uso real por país. Traduce documentos completos sin tocar su diseño, genera citas en APA, AMA o Vancouver y audita la bibliografía de cualquier PDF contra Crossref y PubMed.": { en: "Bidirectional medical translation specialized in acronyms, abbreviations, contractions and eponyms—including real-world usage by country. Translate complete documents without altering their layout, generate APA, AMA or Vancouver citations, and audit any PDF bibliography against Crossref and PubMed.", pt: "Tradução médica bidirecional especializada em siglas, abreviações, contrações e epônimos — incluindo o uso real por país. Traduza documentos completos sem alterar o layout, gere citações APA, AMA ou Vancouver e audite a bibliografia de qualquer PDF no Crossref e PubMed." },
  "Cada término, sigla y referencia puede cotejarse con PubMed, la OMS, MedlinePlus, DeCS, Cochrane, Crossref y manuales veterinarios, con enlace a la fuente.": { en: "Every term, acronym and reference can be checked against PubMed, WHO, MedlinePlus, DeCS, Cochrane, Crossref and veterinary manuals, with a link to the source.", pt: "Cada termo, sigla e referência pode ser verificado no PubMed, OMS, MedlinePlus, DeCS, Cochrane, Crossref e manuais veterinários, com link para a fonte." },
  "MedLingua es una herramienta de apoyo terminológico y editorial. Toda traducción destinada a uso clínico, regulatorio o de publicación debe ser revisada por un profesional cualificado.": { en: "MedLingua is a terminology and editorial support tool. Any translation intended for clinical, regulatory or publishing use must be reviewed by a qualified professional.", pt: "O MedLingua é uma ferramenta de apoio terminológico e editorial. Toda tradução destinada ao uso clínico, regulatório ou à publicação deve ser revisada por um profissional qualificado." },
  "Ctrl/⌘ + Intro no necesario · usa Traducir": { en: "No need for Ctrl/⌘ + Enter · use Translate", pt: "Não é necessário Ctrl/⌘ + Enter · use Traduzir" },
  "Texto a revisar": { en: "Text to proofread", pt: "Texto para revisar" },
  "Resultado de la corrección": { en: "Proofreading result", pt: "Resultado da revisão" },
  "Revisión ortográfica y médica": { en: "Spelling and medical review", pt: "Revisão ortográfica e médica" },
  "Advertencias de seguridad": { en: "Safety warnings", pt: "Alertas de segurança" },
  "Abreviaturas de riesgo y buenas prácticas": { en: "High-risk abbreviations and best practices", pt: "Abreviações de risco e boas práticas" },
  "Ordenadas por gravedad": { en: "Sorted by severity", pt: "Ordenadas por gravidade" },
  "Ordenados por aparición — severidad y categoría para cada uno": { en: "Sorted by appearance—with severity and category for each", pt: "Ordenados por aparição — com gravidade e categoria de cada um" },
  "Notas del traductor": { en: "Translator notes", pt: "Notas do tradutor" },
  "Decisiones terminológicas": { en: "Terminology decisions", pt: "Decisões terminológicas" },
  "Editor bilingüe": { en: "Bilingual editor", pt: "Editor bilíngue" },
  "Edita cualquier línea antes de descargar. Los cambios se aplican al archivo final.": { en: "Edit any line before downloading. Changes are applied to the final file.", pt: "Edite qualquer linha antes de baixar. As alterações são aplicadas ao arquivo final." },
  "Corrige cualquier segmento: los cambios se aplican al archivo descargado": { en: "Edit any segment; changes are applied to the downloaded file", pt: "Corrija qualquer segmento; as alterações são aplicadas ao arquivo baixado" },
  "Analizando el documento…": { en: "Analyzing document…", pt: "Analisando documento…" },
  "Analizando estructura y contenido": { en: "Analyzing structure and content", pt: "Analisando estrutura e conteúdo" },
  "Extrayendo el texto del PDF": { en: "Extracting text from PDF", pt: "Extraindo texto do PDF" },
  "Traduciendo segmentos…": { en: "Translating segments…", pt: "Traduzindo segmentos…" },
  "Generando el informe": { en: "Generating report", pt: "Gerando relatório" },
  "Generando…": { en: "Generating…", pt: "Gerando…" },
  "Preparando": { en: "Preparing", pt: "Preparando" },
  "Extrayendo": { en: "Extracting", pt: "Extraindo" },
  "Subiendo": { en: "Uploading", pt: "Enviando" },
  "Subiendo archivo para transcripción…": { en: "Uploading file for transcription…", pt: "Enviando arquivo para transcrição…" },
  "Transcribiendo el audio a texto…": { en: "Transcribing audio to text…", pt: "Transcrevendo áudio para texto…" },
  "La IA está procesando el audio…": { en: "AI is processing the audio…", pt: "A IA está processando o áudio…" },
  "Transcripción lista": { en: "Transcription ready", pt: "Transcrição pronta" },
  "Generado automáticamente a partir de la transcripción": { en: "Automatically generated from the transcription", pt: "Gerado automaticamente a partir da transcrição" },
  "Conversión local": { en: "Local conversion", pt: "Conversão local" },
  "Convirtiendo el video a audio comprimido…": { en: "Converting video to compressed audio…", pt: "Convertendo vídeo em áudio compactado…" },
  "Calidad alta": { en: "High quality", pt: "Qualidade alta" },
  "Calidad media — revisar": { en: "Medium quality—review", pt: "Qualidade média — revisar" },
  "Calidad baja — corregir": { en: "Low quality—correct", pt: "Qualidade baixa — corrigir" },
  "DOI, PMID, referencia en cualquier estilo o sube el artículo completo": { en: "DOI, PMID, reference in any style, or upload the full article", pt: "DOI, PMID, referência em qualquer estilo ou envie o artigo completo" },
  "Leyendo documento · extrayendo metadatos · validando en Crossref": { en: "Reading document · extracting metadata · validating in Crossref", pt: "Lendo documento · extraindo metadados · validando no Crossref" },
  "Leyendo el documento · identificando título, autores, DOI · validando en Crossref": { en: "Reading document · identifying title, authors and DOI · validating in Crossref", pt: "Lendo documento · identificando título, autores e DOI · validando no Crossref" },
  "Resolviendo DOI · consultando Crossref · comprobando PubMed": { en: "Resolving DOI · querying Crossref · checking PubMed", pt: "Resolvendo DOI · consultando Crossref · verificando PubMed" },
  "Reconstruida con los metadatos oficiales de Crossref": { en: "Rebuilt with official Crossref metadata", pt: "Reconstruída com os metadados oficiais do Crossref" },
  "Analizando artículo": { en: "Analyzing article", pt: "Analisando artigo" },
  "Localizando citas y bibliografía": { en: "Locating citations and bibliography", pt: "Localizando citações e bibliografia" },
  "Cruce cita ↔ referencia": { en: "Citation ↔ reference cross-check", pt: "Cruzamento citação ↔ referência" },
  "Cotejando cada referencia en Crossref y PubMed": { en: "Checking each reference in Crossref and PubMed", pt: "Verificando cada referência no Crossref e PubMed" },
  "Comprobando que las fuentes sustentan lo citado": { en: "Checking that sources support the cited claims", pt: "Verificando se as fontes sustentam as afirmações citadas" },
  "Existencia real": { en: "Real existence", pt: "Existência real" },
  "Coherencia de contenido": { en: "Content consistency", pt: "Coerência de conteúdo" },
  "Retractaciones": { en: "Retractions", pt: "Retratações" },
  "Citas huérfanas y referencias nunca citadas.": { en: "Orphan citations and references that are never cited.", pt: "Citações órfãs e referências nunca citadas." },
  "DOI, título, autores, revista y año contra Crossref/PubMed.": { en: "DOI, title, authors, journal and year checked against Crossref/PubMed.", pt: "DOI, título, autores, periódico e ano verificados no Crossref/PubMed." },
  "¿La fuente sustenta lo que se afirma? Multilingüe.": { en: "Does the source support the claim? Multilingual.", pt: "A fonte sustenta a afirmação? Multilíngue." },
  "Alerta si el estudio fue retractado.": { en: "Alerts if the study was retracted.", pt: "Alerta se o estudo foi retratado." },
  "Revisar antes de usar clínicamente": { en: "Review before clinical use", pt: "Revisar antes do uso clínico" },
  "Conservar sigla original": { en: "Keep original acronym", pt: "Manter sigla original" },
  "Añade la sigla de origen entre paréntesis.": { en: "Adds the source acronym in parentheses.", pt: "Adiciona a sigla original entre parênteses." },
  "Expandir abreviaturas": { en: "Expand abbreviations", pt: "Expandir abreviações" },
  "Desarrolla toda abreviatura o contracción.": { en: "Expands every abbreviation or contraction.", pt: "Desenvolve todas as abreviações ou contrações." },
  "Retrotraducción": { en: "Back translation", pt: "Retrotradução" },
  "Control de calidad al idioma de origen.": { en: "Quality check against the source language.", pt: "Controle de qualidade no idioma de origem." },
  "La traducción se escribe encima del original: se conservan imágenes, tablas, sellos y maquetación.": { en: "The translation is written over the original while preserving images, tables, stamps and layout.", pt: "A tradução é escrita sobre o original, preservando imagens, tabelas, selos e diagramação." },
  "Se reescriben solo los nodos de texto del OOXML: estilos, numeración, tablas e imágenes intactos.": { en: "Only OOXML text nodes are rewritten; styles, numbering, tables and images remain intact.", pt: "Somente os nós de texto OOXML são reescritos; estilos, numeração, tabelas e imagens permanecem intactos." },
  "Cada cuadro de texto y las notas del orador se traducen sin tocar el diseño de las diapositivas.": { en: "Every text box and speaker note is translated without altering the slide design.", pt: "Cada caixa de texto e nota do apresentador é traduzida sem alterar o design dos slides." },
  "Variante por país": { en: "Country variant", pt: "Variante por país" },
  "Ninguna": { en: "None", pt: "Nenhuma" },
  "Ninguno": { en: "None", pt: "Nenhum" },
  "Todos": { en: "All", pt: "Todos" },
  "Pendientes": { en: "Pending", pt: "Pendentes" },
  "Editados": { en: "Edited", pt: "Editados" },
  "Cada token puede cotejarse contra PubMed, ISMP y portales científicos": { en: "Every token can be checked against PubMed, ISMP and scientific databases", pt: "Cada token pode ser verificado no PubMed, ISMP e portais científicos" },
  "Cada término puede cotejarse contra portales científicos": { en: "Every term can be checked against scientific databases", pt: "Cada termo pode ser verificado em portais científicos" },
  "Cotejo en portales científicos": { en: "Scientific database verification", pt: "Verificação em portais científicos" },
  "Seguridad del paciente": { en: "Patient safety", pt: "Segurança do paciente" },
  "Ortografía": { en: "Spelling", pt: "Ortografia" },
  "Tipografía": { en: "Typography", pt: "Tipografia" },
  "Ortotipografía": { en: "Orthotypography", pt: "Ortotipografia" },
  "Abreviatura": { en: "Abbreviation", pt: "Abreviação" },
  "Acrónimo": { en: "Acronym", pt: "Sigla" },
  "Contracción": { en: "Contraction", pt: "Contração" },
  "Epónimo": { en: "Eponym", pt: "Epônimo" },
  "Fármaco": { en: "Drug", pt: "Fármaco" },
  "Unidad": { en: "Unit", pt: "Unidade" },
  "Idioma detectado automáticamente": { en: "Language detected automatically", pt: "Idioma detectado automaticamente" },
  "El idioma se detectará automáticamente al traducir": { en: "The language will be detected automatically when translating", pt: "O idioma será detectado automaticamente ao traduzir" },
  "Idioma detectado": { en: "Detected language", pt: "Idioma detectado" },
  "Estudio o referencia": { en: "Study or reference", pt: "Estudo ou referência" },
  "Autoría no identificada": { en: "Unidentified authorship", pt: "Autoria não identificada" },
  "Sin título": { en: "Untitled", pt: "Sem título" },
  "No localizada": { en: "Not found", pt: "Não localizada" },
  "Coincidencia parcial": { en: "Partial match", pt: "Correspondência parcial" },
  "Verificada": { en: "Verified", pt: "Verificada" },
  "El informe aparecerá aquí": { en: "The report will appear here", pt: "O relatório aparecerá aqui" },
  "Sube un documento primero.": { en: "Upload a document first.", pt: "Envie um documento primeiro." },
  "Transcribe el vídeo primero.": { en: "Transcribe the video first.", pt: "Transcreva o vídeo primeiro." },
  "Cada segmento se traduce con terminología MeSH/DeCS, siglas, abreviaturas y variantes por país.": { en: "Each segment is translated using MeSH/DeCS terminology, acronyms, abbreviations and country variants.", pt: "Cada segmento é traduzido com terminologia MeSH/DeCS, siglas, abreviações e variantes por país." },
  "Descarga subtítulos en formato SRT, WebVTT o bilingüe (original + traducción) listos para el reproductor.": { en: "Download player-ready subtitles in SRT, WebVTT or bilingual format (original + translation).", pt: "Baixe legendas prontas para reprodução em SRT, WebVTT ou formato bilíngue (original + tradução)." },
  "IA Gateway speech-to-text con timestamps por segmento. Scribe de ElevenLabs como respaldo con diarización.": { en: "AI Gateway speech-to-text with timestamps per segment. ElevenLabs Scribe provides diarized fallback.", pt: "Speech-to-text via AI Gateway com timestamps por segmento. Scribe da ElevenLabs como alternativa com diarização." },
  "Bilingüe": { en: "Bilingual", pt: "Bilíngue" },
  "Audio": { en: "Audio", pt: "Áudio" },
  "Vídeo": { en: "Video", pt: "Vídeo" },
  "Casos clínicos": { en: "Clinical cases", pt: "Casos clínicos" },
  "Conferencias": { en: "Conferences", pt: "Conferências" },
  "Documentales médicos": { en: "Medical documentaries", pt: "Documentários médicos" },
  "Vídeos para pacientes": { en: "Patient videos", pt: "Vídeos para pacientes" },
  "Estilo": { en: "Style", pt: "Estilo" },
  "Copiar todo": { en: "Copy all", pt: "Copiar tudo" },
  "Copiar resumen": { en: "Copy summary", pt: "Copiar resumo" },
  "Glosario personal": { en: "Personal glossary", pt: "Glossário pessoal" },
  "Los cuatro idiomas base están siempre activos; añade los que necesites": { en: "The four core languages are always active; add any others you need", pt: "Os quatro idiomas base estão sempre ativos; adicione os que precisar" },
  "Pega texto clínico, arrastra un .txt o un PDF — se extraerá el texto": { en: "Paste clinical text or drag in a .txt or PDF—the text will be extracted", pt: "Cole texto clínico ou arraste um .txt ou PDF — o texto será extraído" },
  "PDF · Word · PowerPoint": { en: "PDF · Word · PowerPoint", pt: "PDF · Word · PowerPoint" },
};

export function translateInterfaceCopy(text: string, language: InterfaceLanguage): string {
  if (language === "es") return text;
  const normalized = text.replace(/\s+/g, " ").trim();
  return COPY[normalized]?.[language] ?? text;
}
